version: '3'
services:
  apache:
    image: dp0211/apache-devops
    ports:
      - "8081:80"

  apache-exporter:
    image: lusotycoon/apache-exporter
    ports:
      - "9117:9117"
    depends_on:
      - apache

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

